name: iOS Build IPA

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        
    - name: Setup Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        
    - name: Install CocoaPods
      run: |
        gem install cocoapods
        cd ios && pod install && cd ..
        
    - name: Build iOS Archive
      run: |
        cd ios
        xcodebuild -workspace SafeDealApp.xcworkspace \
                   -scheme SafeDealApp \
                   -configuration Debug \
                   -destination generic/platform=iOS \
                   -archivePath SafeDealApp.xcarchive \
                   archive \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO \
                   CODE_SIGNING_ALLOWED=NO \
                   DEVELOPMENT_TEAM="" \
                   PROVISIONING_PROFILE=""
                   
    - name: Create IPA without signing
      run: |
        cd ios
        
        # Method 1: Try xcodebuild export first
        echo "Trying xcodebuild export..."
        xcodebuild -exportArchive \
          -archivePath SafeDealApp.xcarchive \
          -exportPath ./export \
          -exportOptionsPlist exportOptionsNoSigning.plist \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO || {
            echo "xcodebuild export failed, trying manual IPA creation..."
            
            # Method 2: Manual IPA creation
            mkdir -p Payload/SafeDealApp.app
            cp -r SafeDealApp.xcarchive/Products/Applications/SafeDealApp.app/* Payload/SafeDealApp.app/
            zip -r SafeDealApp.ipa Payload/
          }
        
        # If xcodebuild succeeded, copy the IPA
        if [ -f "./export/SafeDealApp.ipa" ]; then
          cp ./export/SafeDealApp.ipa SafeDealApp.ipa
        fi
        
        echo "IPA creation completed!"
                   
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: SafeDealApp-iOS-IPA
        path: ios/SafeDealApp.ipa
        retention-days: 30
        
    - name: Upload Archive
      uses: actions/upload-artifact@v4
      with:
        name: SafeDealApp-iOS-Archive
        path: ios/SafeDealApp.xcarchive
        retention-days: 30
        
    - name: Build Summary
      run: |
        echo "## 🎉 iOS Build Complete!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📱 Files Created:" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ **SafeDealApp.ipa** - iOS App Package" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ **SafeDealApp.xcarchive** - Xcode Archive" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📋 How to use:" >> $GITHUB_STEP_SUMMARY
        echo "1. Download the IPA file" >> $GITHUB_STEP_SUMMARY
        echo "2. Install on iOS device via iTunes/Xcode" >> $GITHUB_STEP_SUMMARY
        echo "3. Or use AltStore for sideloading" >> $GITHUB_STEP_SUMMARY 