name: iOS Build Simple

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        
    - name: Setup Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        
    - name: Install CocoaPods
      run: |
        gem install cocoapods
        cd ios && pod install && cd ..
        
    - name: Build iOS app
      run: |
        cd ios
        xcodebuild -workspace SafeDealApp.xcworkspace \
                   -scheme SafeDealApp \
                   -configuration Release \
                   -destination generic/platform=iOS \
                   -archivePath SafeDealApp.xcarchive \
                   archive \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGNING_REQUIRED=NO \
                   CODE_SIGNING_ALLOWED=NO
                   
    - name: Create IPA
      run: |
        cd ios
        xcodebuild -exportArchive \
                   -archivePath SafeDealApp.xcarchive \
                   -exportPath ./build \
                   -exportOptionsPlist exportOptions.plist
                   
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: SafeDealApp-iOS
        path: ios/build/SafeDealApp.ipa
        retention-days: 30 